# Generated by Django 4.0.2 on 2022-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channelentry_fieldentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelentry',
            name='field1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field3',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field4',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field5',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field6',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field7',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='channelentry',
            name='field8',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
